### ISSUE TITLE
Draw image structure

### ISSUE THREAD

**Issue by Eomm** [Eomm/fastify-overview#13]
This plugin has one main focus: let the developer build a graphical representation of the Fastify application.

A draw by hand example:

![image](https://user-images.githubusercontent.com/11404065/140822275-8c2b8dc4-0448-4e31-a7cb-0090160dfd1e.png)

The image (or dynamic image) should show:

### the main tree structure

Fastify builds a tree internally, that is represented by this plugin through its structure:

```
const appStructure = app.overview()
appStructure.children.forEach(child => {
   child.children.forEach() //.... etc
})
```

### the hooks

Every node has a `node.hooks` object that maps every hook added to that node.
We should find how to draw this information

### the decorator

As the hooks object, every node has the `node.decorators` object that maps the decorators added to that node.
We should find how to draw this information

### the routes

This information is not tracked yet but adding the routes would complete the whole application schema representation.
We should find how to draw this information

Doing so would:

- ease the documentation
- give to the user a complete overview of the application
- find potential issue without even reading the code
- ease the debugging

## How to do that

I think that the image representation should be simple.
I don't have a strong opinion on which technology adopt.
I would just create an endpoint that shows an image or a webpage if we build dynamic images.
Feel free to propose what you prefer

**Comment by simoneb** [comment]
@Eomm @brainrepo what kind of support is needed on this issue?

**Comment by raul-saez** [comment]
@Eomm @simoneb I've started taking a look into this.

**Comment by simoneb** [comment]
- [ ] improve and complete the radial visualization
- [ ] expose a route to return the json data
- [ ] update the logic to align with the current version of the data structure (which has changed since then)
- [ ] when you click on one node the details pop up
- [ ] support navigating to code when clicking on a node
- [ ] embed the ui in the plugin itself

**Comment by Eomm** [comment]
Done in https://github.com/nearform/fastify-overview-ui/releases/tag/v1.0.1
