### ISSUE TITLE
Show node details sidebar

### ISSUE THREAD

**Issue by raul-saez** [Eomm/fastify-overview#36]
Add a sidebar which displays a breakdown of the node details when clicked on.

Example (Screenshot from first proposal):
![image](https://user-images.githubusercontent.com/58308949/165492132-1acf2a75-622d-4458-9e75-f59e63d13941.png)

**Comment by raul-saez** [comment]
This is not needed after committing to the radial representation of the graph. All the information available on this sidebar is essentially already represented on the graph.

**Comment by Eomm** [comment]
Now I remember the use case: routes may have their own hooks, so those values were not shown in the radial graph.

Is this use case covered now?

**Comment by raul-saez** [comment]
> Now I remember the use case: routes may have their own hooks, so those values were not shown in the radial graph.
> 
> Is this use case covered now?

Yeah, this should already be covered. 
For example:
![Screenshot 2022-05-03 at 16 50 21](https://user-images.githubusercontent.com/58308949/166488792-393c778d-7a15-483f-bd05-b26bb2410bb5.png)
